Repository HPInc/ml-git, pull requests merged in 2020-11, with the labels that each got.

#41 Adding the code of conduct to the project
  CODE_OF_CONDUCT.md
Labels: documentation

#38 Update command to warn the user if a remote is already set
  ml_git/admin.py
  ml_git/ml_git_message.py
  tests/integration/test_02_add_remote.py
Labels: feature

#40 Create command to remove remote configuration
  docs/mlgit_commands.md
  docs/mlgit_internals.md
  ml_git/_metadata.py
  ml_git/admin.py
  ml_git/commands/remote.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/commands.py
  tests/integration/test_34_remote_del.py
  tests/unit/test_admin.py
  tests/unit/test_metadata.py
Labels: feature

#44 Adjusting the Boto3 session startup
  docs/mlgit_commands.md
  docs/s3_configurations.md
  ml_git/admin.py
  ml_git/commands/store.py
  ml_git/ml_git_message.py
  ml_git/storages/s3store.py
  ml_git/storages/store_utils.py
  tests/integration/commands.py
  tests/integration/helper.py
  tests/integration/test_03_add_store.py
  tests/integration/test_07_push_files.py
  tests/unit/test_admin.py
Labels: bugfix

#46 Providing create command available through ML Git API
  README.md
  docs/api/README.md
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb
  docs/api/quick_start.md
  ml_git/api.py
  tests/integration/test_24_api.py
Labels: feature

#49 Migrating asciinema videos to new account
  README.md
  docs/first_project.md
  docs/s3_configurations.md
Labels: documentation

#45 Creating a example of storage reuse with multiple datasets
  docker/Dockerfile
  docker/local_ml_git_config_server.git.tar.xz
  docs/api/api_scripts/multiple_datasets_notebook/famous_faces.jpg
  docs/api/api_scripts/multiple_datasets_notebook/famous_faces/famous_faces.zip
  docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/people_faces.jpg
  docs/api/api_scripts/multiple_datasets_notebook/people_faces/people_faces.zip
Labels: documentation

#48 Modifying status command to show summary information
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/commands.py
  tests/integration/test_34_remote_del.py
  tests/integration/test_35_status_short_mode.py
  tests/unit/test_utils.py
Labels: enhancement, feature

#57 Fixing github actions and windows build script
  .github/workflows/release-workflow.yml
  Pipfile
  Pipfile.lock
  scripts/build/compile/build.bat
Labels: hotfix

#47 Adding documentation about tabular data recommended patterns
  README.md
  docs/tabular_data/partioned_data.png
  docs/tabular_data/tabular_data.md
  docs/tabular_data/tabular_data.png
Labels: documentation

#50 Modifying the status command to receive a directory path as an argument
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/file_system/local.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/commands.py
  tests/integration/test_36_status_path_directory.py
Labels: enhancement, feature

#51 Creating gc command to remove unnecessary files
  Pipfile
  Pipfile.lock
  docs/mlgit_commands.md
  docs/mlgit_internals.md
  ml_git/commands/repository.py
  ml_git/file_system/cache.py
  ml_git/file_system/index.py
  ml_git/file_system/objects.py
  ml_git/metadata.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/commands.py
  tests/integration/output_messages.py
  tests/integration/test_36_gc.py
  tests/unit/test_hashfs.py
  tests/unit/test_local.py
  tests/unit/test_s3_store.py
  tests/unit/test_utils.py
Labels: feature

#55 Providing commands to support project initialization through API
  docs/api/README.md
  docs/api/api_scripts/basic_flow.ipynb
  docs/api/quick_start.md
  ml_git/api.py
  ml_git/constants.py
  tests/integration/test_24_api.py
Labels: feature

#42 Adding issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#53 Fixing reset hard command with data in subdirectories
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/test_12_reset_command.py
  tests/unit/test_utils.py
Labels: bugfix

#52 Adding new files based on an old tag
  ml_git/_metadata.py
  ml_git/repository.py
  tests/integration/helper.py
  tests/integration/test_08_checkout_tag.py
Labels: bugfix
