Repository HPInc/ml-git, pull requests merged in 2020-12, with the labels that each got.

#61 Fixing the installation process
  ml_git/version.info
  ml_git/version.py
  scripts/build/compile/build.bat
  scripts/build/compile/build.sh
  setup.py
Labels: bugfix

#54 Adding support for data specialization plugins
  README.md
  docs/plugins.md
  ml_git/metadata.py
  ml_git/plugin_interface/__init__.py
  ml_git/plugin_interface/data_plugin_constants.py
  ml_git/plugin_interface/plugin_especialization.py
  tests/unit/test_plugin_caller.py
Labels: feature

#56 Creation of entity type validation
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/test_24_api.py
Labels: enhancement, feature

#62 Creating script to automate the creation of repos and buckets
  docs/first_project.md
  scripts/resources_initialization/README.md
  scripts/resources_initialization/resources_initialization.bat
  scripts/resources_initialization/resources_initialization.sh
Labels: feature

#63 Updating the term "store" to "storage" in the CLI commands.
  docs/mlgit_commands.md
  ml_git/commands/__init__.py
  ml_git/commands/descriptor.py
  ml_git/commands/help_msg.py
  ml_git/commands/storage.py
  ml_git/commands/store.py
Labels: feature

#64 Fixing 'HEAD is a detached symbolic reference' error
  ml_git/_metadata.py
  ml_git/constants.py
Labels: bugfix
