Repository HPInc/ml-git, pull requests merged in 2021-05, with the labels that each got.

#105 Fixing issue in S3 bucket region
  ml_git/storages/store_utils.py
Labels: hotfix

#102 Improvement in bumpversion option
  ml_git/metadata.py
  ml_git/repository.py
  ml_git/spec.py
  tests/integration/test_05_add_files.py
  tests/integration/test_06_commit_files.py
  tests/integration/test_07_push_files.py
  tests/integration/test_08_checkout_tag.py
  tests/integration/test_11_list_tag.py
  tests/integration/test_12_reset_command.py
  tests/integration/test_16_show.py
  tests/integration/test_24_api.py
  tests/integration/test_28_checkout_bare.py
  tests/unit/test_metadata.py
  tests/unit/test_spec.py
Labels: enhancement

#104 Adding the fail_limit option for push and checkout
  docs/api/README.md
  docs/mlgit_commands.md
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/error_handler.py
  ml_git/file_system/local.py
  ml_git/ml_git_message.py
  ml_git/pool.py
  ml_git/repository.py
  tests/integration/test_08_checkout_tag.py
  tests/unit/test_error_handler.py
Labels: feature
