Repository HPInc/ml-git, pull requests merged in 2021-06, with the labels that each got.

#112 Minio resource initialization
  docs/resources_initialization.md
  scripts/resources_initialization/resources_initialization.bat
  scripts/resources_initialization/resources_initialization.sh
Labels: documentation, enhancement

#110 How to contribute documentation
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
  README.md
Labels: documentation

#109 Log file implementation
  ml_git/constants.py
  ml_git/log.py
  ml_git/ml_git_message.py
  tests/unit/test_log.py
Labels: feature

#113 Adding commands to support config versioning
  docs/api/README.md
  docs/first_project.md
  docs/mlgit_commands.md
  docs/mlgit_internals.md
  ml_git/_metadata.py
  ml_git/admin.py
  ml_git/api.py
  ml_git/commands/general.py
  ml_git/commands/remote.py
  ml_git/commands/repository.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/commands.py
  tests/integration/conftest.py
  tests/integration/test_20_clone.py
  tests/integration/test_24_api.py
  tests/integration/test_33_config.py
  tests/integration/test_34_remote_del.py
  tests/unit/test_metadata.py
  tests/unit/test_utils.py
Labels: feature

#111 Integrating relationship api
  Pipfile
  Pipfile.lock
  docs/api/README.md
  docs/api/api_scripts/relationship_notebook/list_entities.ipynb
  docs/api/quick_start.md
  ml_git/api.py
  ml_git/relationship/__init__.py
  ml_git/relationship/entity_manager.py
  ml_git/relationship/github_manager.py
  ml_git/relationship/models/__init__.py
  ml_git/relationship/models/config.py
  ml_git/relationship/models/entity.py
  ml_git/relationship/utils.py
  tests/unit/test_api.py
Labels: feature

#106 Fixing problem when adding README files
  ml_git/file_system/index.py
  ml_git/file_system/local.py
  tests/integration/test_05_add_files.py
Labels: bugfix
