Repository HPInc/ml-git, pull requests merged in 2021-11, with the labels that each got.

#186 Format diff command output
  ml_git/constants.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/commands.py
  tests/integration/helper.py
  tests/integration/test_39_diff_command.py
  tests/unit/test_metadata.py
Labels: feature

#183 Changes in Metadata to support diff command
  ml_git/_metadata.py
  ml_git/constants.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/commands.py
  tests/integration/helper.py
  tests/integration/test_39_diff_command.py
  tests/unit/test_metadata.py
Labels: feature

#184 Updating documentation to work with the MLGitAPI class
  docs/api/README.md
  docs/api/quick_start.md
Labels: documentation

#181 Creating MLGitAPI to allow multiple projects in the same script
  docs/api/README.md
  docs/api/api_scripts/basic_flow.ipynb
  docs/api/api_scripts/clone_repository.ipynb
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/checkout_with_sample.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
  docs/api/api_scripts/relationship_notebook/relationship_api_commands.ipynb
  docs/api/quick_start.md
  ml_git/api.py
  tests/integration/test_24_api.py
Labels: enhancement

#187 Diff command implementation
  docs/mlgit_commands.md
  ml_git/_metadata.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/constants.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/commands.py
  tests/integration/helper.py
  tests/integration/test_39_diff_command.py
  tests/unit/test_metadata.py
Labels: feature

#185 Creation of notebook example to work with the MLGitAPI class
  docs/api/api_scripts/multiple_projects.ipynb
Labels: enhancement

#191 Fixing the output of the diff command
  ml_git/_metadata.py
  ml_git/constants.py
  ml_git/manifest.py
  tests/integration/test_05_add_files.py
  tests/integration/test_39_diff_command.py
Labels: bugfix

#192 Updating diff methods to compare MANIFEST files
  ml_git/_metadata.py
  ml_git/constants.py
  ml_git/manifest.py
  ml_git/repository.py
  tests/integration/test_39_diff_command.py
  tests/unit/test_metadata.py
Labels: bugfix
