Repository HPInc/ml-git, pull requests merged in 2021-09, with the labels that each got.

#134 Fixing create command message
  docs/api/api_scripts/basic_flow.ipynb
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_cli.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
  docs/api/quick_start.md
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/gdrive_storage/test_32_gdrive_storage.py
  tests/integration/test_19_create.py
Labels: bugfix

#139 Changing the message level in the list command
  docs/mlgit_commands.md
  ml_git/_metadata.py
  ml_git/commands/repository.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_17_list.py
Labels: bugfix

#135 Fixing help messages with ellipsis
  ml_git/commands/descriptor.py
Labels: bugfix

#141 Updating Pipfile.lock and How to Install section
  Pipfile.lock
  README.md
Labels: bugfix

#140 SSH key generation fix on integration tests with make
  scripts/run_integration_tests.bat
Labels: bugfix

#137 Remove metric options from add command for dataset and labels
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  tests/integration/test_05_add_files.py
  tests/integration/test_29_log.py
Labels: bugfix

#144 Fixing the user's git credential input
  ml_git/_metadata.py
  ml_git/git_client.py
  ml_git/ml_git_message.py
Labels: bugfix

#142 Fixing issue when ml-git tries to clone ml entities repository and there are blank spaces in the project folder path
  ml_git/git_client.py
  tests/integration/test_04_init_entity.py
Labels: bugfix

#138 Adding ML-Git Uninstall Section
  README.md
Labels: bugfix

#143 Stopping graph command when no relationship is found
  ml_git/ml_git_message.py
  ml_git/relationship/local_entity_manager.py
  tests/integration/test_24_api.py
Labels: bugfix

#146 Display entities with no relationship on graph
  ml_git/relationship/utils.py
  tests/integration/test_24_api.py
Labels: bugfix

#145 Add error log message when using a minio endpoint that is not running
  ml_git/ml_git_message.py
  ml_git/storages/s3_storage.py
  tests/integration/test_07_push_files.py
Labels: bugfix

#147 Fixing some command erros in the docs
  docs/first_project.md
  docs/mlgit_commands.md
  docs/qs_configure_repository.md
Labels: documentation

#148 Fixing error when using graph command and the configured remote is empty
  ml_git/ml_git_message.py
  ml_git/relationship/local_entity_manager.py
  ml_git/repository.py
  tests/integration/test_15_update.py
  tests/integration/test_24_api.py
Labels: bugfix

#149 Updating methods to use the version number to order entities
  ml_git/relationship/local_entity_manager.py
  tests/integration/test_24_api.py
Labels: bugfix

#150 Fixing invalid directory handling in status command
  ml_git/file_system/local.py
  tests/integration/test_36_status_path_directory.py
Labels: bugfix

#151 Fixing error when ssh host is first accessed
  ml_git/git_client.py
Labels: bugfix

#159 Update --category option by --categories when using ml-entity create command
  README.md
  docs/advanced_scenarios.md
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_cli.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
  docs/first_project.md
  docs/first_steps.md
  docs/mlgit_commands.md
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/help_msg.py
  ml_git/repository.py
  tests/integration/gdrive_storage/test_32_gdrive_storage.py
  tests/integration/test_19_create.py
  tests/integration/test_37_sftp_storage.py
Labels: feature

#160 Updating docs to use MinIO by default
  docs/advanced_scenarios.md
  docs/first_project.md
  docs/first_steps.md
  docs/qs_configure_repository.md
Labels: documentation

#161 Updating docs to teach how to configure MinIO
  docs/aws_s3_configuration.md
  docs/first_project.md
  docs/minio_s3_configuration.md
  docs/storage_configurations.md
  mkdocs.yml
Labels: documentation

#153 Fixing Python version in release workflow
  .github/workflows/release-workflow.yml
Labels: bugfix

#162 Adding range validator to --version parameter of the create command
  ml_git/commands/descriptor.py
  tests/integration/test_19_create.py
Labels: bugfix

#171 Updating create command documentation
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
Labels: documentation, bugfix

#165 Adding warning message when user uses unnecessary option in command
  ml_git/commands/custom_options.py
  ml_git/ml_git_message.py
  tests/integration/test_19_create.py
  tests/integration/test_38_models_metrics.py
Labels: enhancement

#166 Removing files created during an aborted command execution
  ml_git/repository.py
Labels: bugfix

#163 Updating ml-git documentation with the available storage-types
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
  ml_git/commands/help_msg.py
  ml_git/constants.py
Labels: documentation, bugfix

#164 Adding custom type to validate empty strings and strip values automatically
  ml_git/commands/descriptor.py
  ml_git/ml_git_message.py
  ml_git/utils.py
  tests/integration/test_19_create.py
Labels: bugfix

#168 Adding messages when using the unzip option in the create command
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/test_19_create.py
Labels: enhancement

#169 Inserting validation for categories names in --categories option when the ml-git entity create command is used
  ml_git/commands/custom_types.py
  ml_git/commands/descriptor.py
  ml_git/constants.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/test_19_create.py
Labels: bugfix

#173 Fixing the problem of configuring an sftp bucket with the wizard option
  ml_git/config.py
  ml_git/repository.py
  tests/unit/conftest.py
  tests/unit/test_config.py
Labels: bugfix

#167 Adding info message when .spec is added automatically to staged files
  ml_git/file_system/index.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_05_add_files.py
  tests/integration/test_06_commit_files.py
Labels: bugfix

#175 Fixing issue related with storage type s3h being saving in global configuration instead of local configuration
  ml_git/config.py
  tests/unit/test_config.py
Labels: bugfix

#170 Adding custom type to validate empty strings in entity-dir param of create commend
  ml_git/commands/descriptor.py
  ml_git/repository.py
  tests/integration/test_19_create.py
Labels: bugfix

#174 Removing special character from commands documentation
  README.md
  docs/advanced_scenarios.md
  docs/aws_s3_configuration.md
  docs/azure_configurations.md
  docs/first_project.md
  docs/first_steps.md
  docs/gdrive_configurations.md
  docs/installation_guide.md
  docs/minio_s3_configuration.md
  docs/mlgit_commands.md
  docs/qs_checkout.md
  docs/qs_configure_repository.md
  docs/sftp_configurations.md
Labels: bugfix

#179 Avoiding creating a default bucket when initializing a project
  docs/advanced_scenarios.md
  docs/centralized_cache_and_objects.md
  docs/first_project.md
  docs/gdrive_configurations.md
  ml_git/config.py
  tests/integration/test_24_api.py
  tests/integration/test_33_config.py
  tests/unit/test_config.py
Labels: bugfix
