Repository HPInc/ml-git, pull requests merged in 2021-01, with the labels that each got.

#65 Changing log command to show informations about specialized data.
  docs/plugins.md
  ml_git/_metadata.py
  ml_git/plugin_interface/data_plugin_constants.py
  ml_git/repository.py
  tests/unit/test_metadata.py
Labels: feature

#69 [plural entity names] Adding support to plural entity names
  ml_git/_metadata.py
  ml_git/admin.py
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/general.py
  ml_git/commands/remote.py
  ml_git/commands/utils.py
  ml_git/config.py
  ml_git/constants.py
  ml_git/file_system/local.py
  ml_git/metadata.py
  ml_git/ml_git_message.py
  ml_git/refs.py
  ml_git/repository.py
  ml_git/spec.py
  ml_git/utils.py
Labels: feature

#68 Implementation of sftp storage.
  .gitignore
  Pipfile
  Pipfile.lock
  docs/mlgit_commands.md
  docs/sftp_configurations.md
  docs/storage_configurations.md
  ml_git/admin.py
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/help_msg.py
  ml_git/commands/storage.py
  ml_git/constants.py
  ml_git/ml_git_message.py
  ml_git/storages/sftp_store.py
  ml_git/storages/store_utils.py
  scripts/run_integration_tests.bat
  scripts/run_integration_tests.sh
  tests/integration/helper.py
  tests/integration/test_37_sftp_storage.py
Labels: enhancement, feature

#72 [plural entity names] Updating documentation to use plural entity names
  README.md
  docker/README.md
  docker/init.sh
  docs/api/README.md
  docs/api/api_scripts/basic_flow.ipynb
  docs/api/api_scripts/checkout_with_sample.ipynb
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_cli.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
  docs/api/quick_start.md
  docs/centralized_cache_and_objects.md
  docs/first_project.md
  docs/gdrive_configurations.md
  docs/mlgit_commands.md
  docs/mlgit_internals.md
  docs/mutability_helper.md
  docs/plugins.md
  docs/qs_checkout.md
  docs/qs_configure_repository.md
Labels: documentation

#80 Updating demo videos
  README.md
  docs/first_project.md
Labels: documentation

#76 [redefine storage setup] Redefining setup cloud storage link (store/storage)
  ml_git/admin.py
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/commands/storage.py
  ml_git/commands/store.py
  ml_git/config.py
  ml_git/constants.py
  ml_git/file_system/hashfs.py
  ml_git/file_system/local.py
  ml_git/file_system/objects.py
  ml_git/metadata.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/spec.py
  ml_git/storages/azure_storage.py
  ml_git/storages/google_drive_storage.py
  ml_git/storages/multihash_storage.py
  ml_git/storages/s3_storage.py
  ml_git/storages/storage.py
  ml_git/storages/store_utils.py
  ml_git/utils.py
Labels: feature

#79 [redefine storage setup] Updating documentation to use storage instead of store
  README.md
  docs/api/README.md
  docs/api/api_scripts/basic_flow.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
  docs/api/quick_start.md
  docs/centralized_cache_and_objects.md
  docs/developer_info.md
  docs/first_project.md
  docs/gdrive_configurations.md
  docs/mlgit_commands.md
  docs/mlgit_internals.md
  docs/mutability_helper.md
  docs/plugins.md
  docs/qs_configure_repository.md
Labels: documentation
