Repository HPInc/ml-git, pull requests merged in 2021-03, with the labels that each got.

#89 Hardcoded migration on ml_git core and tests.
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/config.py
  ml_git/constants.py
  ml_git/file_system/index.py
  ml_git/file_system/local.py
  ml_git/metadata.py
  ml_git/repository.py
  tests/integration/gdrive_storage/test_32_gdrive_storage.py
  tests/integration/helper.py
  tests/integration/test_03_add_store.py
  tests/integration/test_19_create.py
  tests/integration/test_23_metadata_persistence.py
  tests/integration/test_24_api.py
  tests/integration/test_25_export.py
  tests/integration/test_26_mutability.py
  tests/integration/test_27_unlock.py
  tests/integration/test_28_checkout_bare.py
  tests/integration/test_30_azure_storage.py
  tests/integration/test_31_push_api.py
  tests/integration/test_37_sftp_storage.py
  tests/unit/conftest.py
  tests/unit/test_admin.py
  tests/unit/test_config.py
  tests/unit/test_local.py
  tests/unit/test_metadata.py
  tests/unit/test_refs.py
  tests/unit/test_s3_storage.py
  tests/unit/test_spec.py
  tests/unit/test_utils.py
Labels: enhancement, feature

#92 Improve Gdrive performance
  Pipfile
  Pipfile.lock
  ml_git/ml_git_message.py
  ml_git/storages/google_drive_storage.py
  ml_git/utils.py
  tests/integration/gdrive_storage/test_32_gdrive_storage.py
  tests/integration/test_19_create.py
  tests/unit/test_gdrive_storage.py
Labels: enhancement

#95 Fixing bug in log command with data specialization
  ml_git/_metadata.py
  ml_git/repository.py
  tests/unit/test_metadata.py
Labels: bugfix

#93 Adding models metrics command to show metrics
  docs/first_project.md
  docs/mlgit_commands.md
  ml_git/_metadata.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/constants.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/commands.py
  tests/integration/test_38_models_metrics.py
  tests/unit/conftest.py
  tests/unit/test_metadata.py
  tests/unit/test_utils.py
Labels: feature

#94 Providing metrics command available through API
  docs/api/README.md
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_cli.ipynb
  ml_git/_metadata.py
  ml_git/api.py
  ml_git/repository.py
  tests/integration/helper.py
  tests/integration/test_24_api.py
Labels: feature

#96 Changing keys in configuration files
  docs/centralized_cache_and_objects.md
  docs/first_project.md
  docs/gdrive_configurations.md
  docs/mlgit_commands.md
  docs/mlgit_internals.md
  docs/mutability_helper.md
  docs/plugins.md
  ml_git/_metadata.py
  ml_git/admin.py
  ml_git/config.py
  ml_git/constants.py
  ml_git/file_system/local.py
  ml_git/metadata.py
  ml_git/repository.py
  ml_git/spec.py
  ml_git/storages/azure_storage.py
  ml_git/storages/store_utils.py
  ml_git/utils.py
  tests/integration/helper.py
  tests/integration/test_03_add_store.py
  tests/integration/test_05_add_files.py
  tests/integration/test_19_create.py
  tests/integration/test_23_metadata_persistence.py
  tests/integration/test_24_api.py
  tests/integration/test_26_mutability.py
  tests/integration/test_28_checkout_bare.py
  tests/integration/test_33_config.py
  tests/unit/conftest.py
  tests/unit/test_admin.py
  tests/unit/test_config.py
  tests/unit/test_dir/.ml-git/config.yaml
  tests/unit/test_dir/datasets/dataex/dataex.spec
  tests/unit/test_dir/hdata/config.yaml
  tests/unit/test_dir/hdata/dataset-ex.spec
  tests/unit/test_dir/hdata/dataset-spec-3.spec
  tests/unit/test_dir/mdata/metadata/dataset-ex-2/dataset-ex-2.spec
  tests/unit/test_dir/mdata/metadata/dataset-ex/dataset-ex.spec
  tests/unit/test_dir/minit/datasets/index/metadata/dataset-ex/dataset-ex.spec
  tests/unit/test_dir/specdata/bad1/invalid-name.spec
  tests/unit/test_dir/specdata/invalid2.spec
  tests/unit/test_dir/specdata/invalid3.spec
  tests/unit/test_dir/specdata/invalid4.spec
  tests/unit/test_dir/specdata/noaa-severe-weather-inventory/noaa-severe-weather-inventory.spec
  tests/unit/test_dir/specdata/sample.spec
  tests/unit/test_dir/specdata/valid.spec
  tests/unit/test_dir/specdata/valid2.spec
  tests/unit/test_dir/udata/data.yaml
  tests/unit/test_local.py
  tests/unit/test_metadata.py
  tests/unit/test_spec.py
  tests/unit/test_utils.py
Labels: bugfix, enhancement

#98 feature/update documentation
  docs/api/README.md
  docs/api/quick_start.md
  docs/centralized_cache_and_objects.md
  docs/developer_info.md
  docs/first_project.md
  docs/mlgit_commands.md
  docs/mlgit_internals.md
  docs/mutability_helper.md
  docs/plugins.md
  docs/qs_checkout.md
  docs/qs_configure_repository.md
  docs/resources_initialization.md
  docs/storage_configurations.md
Labels: documentation
