Repository HPInc/ml-git, pull requests merged in 2021-07, with the labels that each got.

#114 Adding method in API to list all versions of an entity
  docs/api/README.md
  docs/api/quick_start.md
  ml_git/relationship/entity_manager.py
  ml_git/relationship/models/entity.py
  ml_git/relationship/models/metadata.py
  ml_git/relationship/models/spec_version.py
  ml_git/relationship/models/storage.py
  tests/unit/test_api.py
Labels: feature

#122 Fixing issue in config show command
  ml_git/commands/descriptor.py
  ml_git/commands/help_msg.py
  ml_git/commands/repository.py
  ml_git/config.py
  tests/integration/test_33_config.py
  tests/unit/test_config.py
Labels: bugfix

#123 Fixing problem when adding storage with region
  docs/api/README.md
  docs/mlgit_commands.md
  ml_git/admin.py
  ml_git/api.py
  ml_git/commands/help_msg.py
  ml_git/commands/storage.py
  ml_git/ml_git_message.py
  tests/integration/test_03_add_store.py
  tests/integration/test_24_api.py
Labels: bugfix

#121 Updating required python version and github actions
  .github/workflows/continuous-integration-workflow.yml
  Pipfile
  Pipfile.lock
  README.md
  docs/developer_info.md
  docs/mlgit_internals.md
  tests/integration/helper.py
Labels: enhancement

#124 Fixing wrong message when resources initialization script fails
  scripts/resources_initialization/resources_initialization.bat
  scripts/resources_initialization/resources_initialization.sh
Labels: bugfix

#125 Adding support for defining the .mlgitignore file
  ml_git/constants.py
  ml_git/file_system/index.py
  ml_git/file_system/local.py
  ml_git/metadata.py
  ml_git/ml_git_message.py
  ml_git/utils.py
  tests/integration/helper.py
  tests/integration/test_05_add_files.py
  tests/integration/test_06_commit_files.py
  tests/integration/test_08_checkout_tag.py
  tests/integration/test_09_status_command.py
  tests/unit/test_utils.py
Labels: feature

#117 Adding method in API to get entity relationships
  docs/api/README.md
  docs/api/quick_start.md
  ml_git/relationship/entity_manager.py
  ml_git/relationship/models/entity_version_relationships.py
  ml_git/relationship/utils.py
  tests/unit/test_api.py
Labels: enhancement, feature

#118 Adding method in API to get all entities relationships
  docs/api/README.md
  docs/api/api_scripts/relationship_notebook/list_entities.ipynb
  docs/api/api_scripts/relationship_notebook/relationship_api_commands.ipynb
  docs/api/api_scripts/relationship_notebook/relationship_diagram.png
  docs/api/quick_start.md
  ml_git/relationship/entity_manager.py
  ml_git/relationship/models/config.py
  ml_git/relationship/utils.py
  tests/unit/test_api.py
Labels: enhancement, feature
