Repository HPInc/ml-git, pull requests merged in 2021-02, with the labels that each got.

#84 Adding support for creating an entity with a directory tree
  docs/api/README.md
  docs/first_project.md
  docs/mlgit_commands.md
  docs/mlgit_internals.md
  ml_git/_metadata.py
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/help_msg.py
  ml_git/config.py
  ml_git/file_system/local.py
  ml_git/metadata.py
  ml_git/repository.py
  ml_git/spec.py
  ml_git/utils.py
  tests/integration/gdrive_store/test_32_gdrive_store.py
  tests/integration/helper.py
  tests/integration/test_06_commit_files.py
  tests/integration/test_07_push_files.py
  tests/integration/test_08_checkout_tag.py
  tests/integration/test_09_status_command.py
  tests/integration/test_10_fetch_command.py
  tests/integration/test_11_list_tag.py
  tests/integration/test_12_reset_command.py
  tests/integration/test_13_remote_fsck.py
  tests/integration/test_15_update.py
  tests/integration/test_16_show.py
  tests/integration/test_17_list.py
  tests/integration/test_18_branch.py
  tests/integration/test_19_create.py
  tests/integration/test_21_tag.py
  tests/integration/test_23_metadata_persistence.py
  tests/integration/test_24_api.py
  tests/integration/test_25_export.py
  tests/integration/test_26_mutability.py
  tests/integration/test_28_checkout_bare.py
  tests/integration/test_29_log.py
  tests/integration/test_30_azure_storage.py
  tests/integration/test_32_checkout_otf.py
  tests/integration/test_33_checkout_entity.py
  tests/integration/test_34_remote_del.py
  tests/integration/test_35_status_short_mode.py
  tests/integration/test_36_gc.py
  tests/integration/test_37_sftp_storage.py
  tests/unit/test_metadata.py
  tests/unit/test_spec.py
Labels: feature

#83 Implementation of model metrics
  Pipfile
  Pipfile.lock
  docs/api/README.md
  docs/first_project.md
  docs/mlgit_commands.md
  ml_git/_metadata.py
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/constants.py
  ml_git/file_system/local.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  scripts/run_integration_tests.bat
  scripts/run_integration_tests.sh
  tests/integration/conftest.py
  tests/integration/helper.py
  tests/integration/test_05_add_files.py
  tests/integration/test_29_log.py
  tests/unit/conftest.py
  tests/unit/test_local.py
  tests/unit/test_metadata.py
Labels: enhancement, feature

#85 Updating status command to support data specialization plugins
  docs/plugins.md
  ml_git/constants.py
  ml_git/plugin_interface/data_plugin_constants.py
  ml_git/repository.py
Labels: feature

#86 Fixing missing pytest dependencies for Windows users
  Pipfile
  Pipfile.lock
Labels: bugfix

#87 Fixing create command when used with entity_dir and wizard-config options
  ml_git/repository.py
  ml_git/spec.py
  tests/unit/test_spec.py
Labels: bugfix

#88 Fixing tests that fail when run in a Windows environment
  ml_git/_metadata.py
  tests/integration/conftest.py
  tests/integration/test_05_add_files.py
  tests/integration/test_07_push_files.py
  tests/integration/test_35_status_short_mode.py
  tests/unit/conftest.py
  tests/unit/test_metadata.py
Labels: bugfix
