Repository HPInc/ml-git, pull requests merged in 2022-08, with the labels that each got.

#249 Updating add command to save previous hash when detect corrupted files
  ml_git/file_system/index.py
  ml_git/manifest.py
  ml_git/ml_git_message.py
  tests/integration/test_05_add_files.py
Labels: enhancement

#252 Adding instructions on how to enable autocomplete
  README.md
  docs/shell_completion_guide.md
Labels: documentation

#248 Allowing wizard to activate on parameters with range validation
  ml_git/commands/custom_options.py
  ml_git/commands/descriptor.py
  ml_git/ml_git_message.py
  tests/integration/test_13_remote_fsck.py
Labels: bugfix

#250 Changing fsck to recover the corrupt/missing files
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/file_system/hashfs.py
  ml_git/file_system/index.py
  ml_git/file_system/local.py
  ml_git/log.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_13_remote_fsck.py
  tests/integration/test_14_fsck.py
Labels: enhancement

#254 Feature/update docker env and jupyter notebooks
  .github/workflows/deploy_mkdocs.yml
  docker/Dockerfile
  docker/init.sh
  docs/api/api_scripts/README.md
  docs/api/api_scripts/basic_flow.ipynb
  docs/api/api_scripts/clean_environment.sh
  docs/api/api_scripts/clone_repository.ipynb
  docs/api/api_scripts/mnist_notebook/clean_environment.sh
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb
  docs/api/api_scripts/mnist_notebook/mnist_random_forest_cli.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/checkout_with_sample.ipynb
  docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
  docs/api/api_scripts/multiple_projects.ipynb
  docs/api/api_scripts/relationship_notebook/relationship_api_commands.ipynb
  mkdocs.yml
Labels: documentation

#257 Adding error handling to fsck command
  ml_git/repository.py
  tests/integration/test_14_fsck.py
Labels: bugfix

#256 Adding debug level messages to the config show command
  ml_git/commands/descriptor.py
  ml_git/commands/utils.py
  ml_git/commands/wizard.py
  ml_git/config.py
  ml_git/ml_git_message.py
Labels: enhancement

#255 Updating commands documentation and help message
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
  ml_git/commands/help_msg.py
  ml_git/commands/remote.py
  ml_git/commands/repository.py
Labels: enhancement

#258 Adding click-completion lib
  Pipfile
  Pipfile.lock
  ml_git/commands/general.py
Labels: bugfix

#259 Adding validations for graph command
  ml_git/commands/repository.py
  tests/integration/commands.py
  tests/integration/test_42_graph_command.py
Labels: bugfix

#262 Updating instructions on how to enable bash autocomplete
  docs/shell_completion_guide.md
  ml_git/commands/general.py
Labels: bugfix

#260 Update config push command to check if the file has been changed
  ml_git/_metadata.py
  ml_git/commands/descriptor.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_33_config.py
Labels: bugfix

#265 Updating python version in release workflow
  .github/workflows/release-workflow.yml
Labels: hotfix

#266 Adding bare option in API checkout method
  docs/api/README.md
  ml_git/api.py
  tests/integration/test_24_api.py
Labels: enhancement
