Repository HPInc/ml-git, pull requests merged in 2022-11, with the labels that each got.

#280 Feature/config command
  Pipfile.lock
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/constants.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/commands.py
  tests/integration/test_44_config_command.py
Labels: enhancement

#281 Adding wizard to config command
  docs/api/quick_start.md
  docs/mlgit_commands.md
  docs/mutability_helper.md
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/prompt_msg.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_44_config_command.py
Labels: enhancement

#283 Allowing to change mutability before the entity's first commit
  ml_git/repository.py
  tests/integration/test_44_config_command.py
Labels: bugfix

#284 Fixing mutability default value in wizard
  ml_git/commands/entity.py
  ml_git/commands/utils.py
  tests/integration/test_44_config_command.py
Labels: bugfix

#286 Updating config command --help to display mutability example
  ml_git/commands/descriptor.py
Labels: documentation, enhancement

#285 Fixing relationship data when entities of different types have the same name
  ml_git/relationship/entity_manager.py
  ml_git/relationship/local_entity_manager.py
  ml_git/relationship/utils.py
  tests/integration/test_24_api.py
  tests/unit/test_api.py
Labels: bugfix

#288 Updating commands documentation
  docs/mlgit_commands.md
  ml_git/commands/help_msg.py
Labels: documentation

#287 Updating the documentation for the add, branch, checkout, commit and create commands
  docs/mlgit_commands.md
  ml_git/commands/help_msg.py
Labels: documentation

#289 Fixing typos in commands documentation
  docs/mlgit_commands.md
Labels: documentation
