Repository HPInc/ml-git, pull requests merged in 2022-09, with the labels that each got.

#267 Fixing broken links on notebook summary
  docs/api/api_scripts/README.md
Labels: bugfix

#268 Updating seed default type to integer
  ml_git/commands/descriptor.py
  ml_git/sample.py
Labels: bugfix

#269 Update --full option message in checkout command
  docs/api/README.md
  docs/mlgit_commands.md
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/help_msg.py
Labels: enhancement

#270 Fixing typo error in checkout info message
  ml_git/ml_git_message.py
Labels: bugfix

#271 Updating no-tags found error message to checkout command
  ml_git/ml_git_message.py
Labels: bugfix

#273 Fixing issue with checkout version when repository connection isn't available
  ml_git/file_system/local.py
  ml_git/repository.py
Labels: bugfix

#274 Adding the get command, which allows download a specific file
  docs/api/quick_start.md
  docs/mlgit_commands.md
  ml_git/_metadata.py
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/commands/prompt_msg.py
  ml_git/file_system/local.py
  ml_git/metadata.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/commands.py
  tests/integration/test_33_checkout_entity.py
  tests/integration/test_43_get_command.py
Labels: feature

#272 Updating version of required libs in Pipfile
  Pipfile
  Pipfile.lock
  ml_git/storages/s3_storage.py
  tests/unit/test_local.py
Labels: hotfix

#275 Updating message for fsck command
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_14_fsck.py
Labels: bugfix

#276 Fixing get and checkout with version equals 0
  ml_git/commands/entity.py
  ml_git/commands/wizard.py
  tests/integration/test_33_checkout_entity.py
Labels: bugfix
