Repository HPInc/ml-git, pull requests merged in 2022-03, with the labels that each got.

#195 Updating add command output when it has corrupt files
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_05_add_files.py
Labels: enhancement

#196 Updating checkout command output when it has unsaved files
  ml_git/api.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/file_system/local.py
  ml_git/repository.py
  tests/integration/test_33_checkout_entity.py
Labels: enhancement

#197 Updating remote-fsck command output
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/file_system/hashfs.py
  ml_git/file_system/local.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_13_remote_fsck.py
Labels: enhancement

#198 Updating documentation to reflect changes in command outputs
  docs/api/README.md
  docs/first_project.md
  docs/mlgit_commands.md
Labels: documentation

#202 Adding validation for empty string in metrics-file option
  ml_git/commands/descriptor.py
  tests/integration/test_05_add_files.py
Labels: bugfix

#201 Adding message when executing remote-fsck for empty entity
  ml_git/file_system/local.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_13_remote_fsck.py
  tests/unit/test_local.py
Labels: bugfix

#203 Adding handling for invalid csv file in add command
  ml_git/file_system/local.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_05_add_files.py
Labels: bugfix

#205 Adding treatments in fsck command for repository and entity uninitialized
  ml_git/repository.py
  tests/integration/test_14_fsck.py
Labels: bugfix

#204 Adding message to show the list of missing IPLD
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
  ml_git/file_system/local.py
  ml_git/ml_git_message.py
  tests/integration/test_13_remote_fsck.py
Labels: bugfix

#207 Checking if the user is in a valid directory when running the add command
  ml_git/repository.py
  tests/integration/test_05_add_files.py
Labels: bugfix

#206 Changing the log level for Corruption Detected messages on the remote…
  ml_git/file_system/hashfs.py
  ml_git/ml_git_message.py
  ml_git/storages/multihash_storage.py
  tests/integration/test_13_remote_fsck.py
Labels: bugfix
