Repository HPInc/ml-git, pull requests merged in 2022-06, with the labels that each got.

#119 Adjustment to deploy ml-git release in pypi repository.
  .github/workflows/publish-release.yml
  README.md
  setup.py
Labels: feature

#218 Adding the wizard option to commands that support it
  README.md
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/help_msg.py
  ml_git/commands/storage.py
  ml_git/commands/wizard.py
  ml_git/ml_git_message.py
  tests/integration/test_06_commit_files.py
  tests/integration/test_19_create.py
  tests/integration/test_40_wizard_config.py
Labels: feature

#221 Adding treatment for commit attempt with no data to commit
  ml_git/file_system/objects.py
  ml_git/metadata.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  ml_git/utils.py
  tests/integration/test_06_commit_files.py
  tests/integration/test_23_metadata_persistence.py
  tests/integration/test_24_api.py
  tests/integration/test_29_log.py
  tests/integration/test_33_checkout_entity.py
  tests/integration/test_38_models_metrics.py
Labels: bugfix

#219 Adding use of wizard to port on SFPTH storage
  ml_git/commands/descriptor.py
  ml_git/commands/storage.py
  ml_git/commands/wizard.py
Labels: bugfix

#224 Removing tag option from commit command
  docs/mlgit_commands.md
  ml_git/commands/descriptor.py
Labels: bugfix

#223 Adding method to validate the input in the wizard-config option of create
  ml_git/config.py
  ml_git/ml_git_message.py
  tests/unit/test_config.py
Labels: bugfix

#229 Setting port option to integer type
  ml_git/commands/descriptor.py
  ml_git/commands/storage.py
  ml_git/commands/wizard.py
  tests/integration/test_03_add_store.py
Labels: bugfix

#225 Fixing default value for region not applied when the user inserts whitespace in the answer.
  ml_git/commands/wizard.py
Labels: bugfix

#226 Removing [empty for none] from wizard messages
  ml_git/commands/wizard.py
Labels: bugfix

#227 Checking if have new data before change version in spec
  ml_git/metadata.py
  ml_git/ml_git_message.py
  ml_git/repository.py
  tests/integration/test_06_commit_files.py
Labels: bugfix

#228 Adding use of wizard when user inform invalid storage type
  ml_git/commands/custom_options.py
  ml_git/commands/descriptor.py
  ml_git/commands/entity.py
  ml_git/commands/prompt_msg.py
  ml_git/commands/storage.py
  ml_git/commands/wizard.py
  ml_git/ml_git_message.py
Labels: bugfix

#222 Adding validation for entity name
  ml_git/commands/entity.py
  ml_git/commands/utils.py
  ml_git/constants.py
  ml_git/ml_git_message.py
  tests/integration/test_06_commit_files.py
  tests/integration/test_19_create.py
  tests/integration/test_38_models_metrics.py
  tests/integration/test_40_wizard_config.py
Labels: bugfix

#232 Updating clone command to receive directory as argument
  README.md
  docs/first_project.md
  docs/first_steps.md
  docs/mlgit_commands.md
  docs/qs_checkout.md
  ml_git/admin.py
  ml_git/commands/general.py
  ml_git/ml_git_message.py
  tests/integration/test_20_clone.py
  tests/integration/test_33_config.py
Labels: enhancement

#233 Prompting the version number and message in the commit command
  ml_git/commands/entity.py
  ml_git/commands/prompt_msg.py
  ml_git/commands/utils.py
  ml_git/commands/wizard.py
  tests/integration/test_06_commit_files.py
  tests/integration/test_23_metadata_persistence.py
  tests/integration/test_40_wizard_config.py
Labels: enhancement
